### ISSUE TITLE
Multi-label Classification

### ISSUE THREAD

**Issue by SaraAmd** [he159ok/Towards-More-Accurate-Uncertainty-Estimation-In-Text-Classification#1]
Can this modelbe used for multi-label classification?

**Comment by he159ok** [comment]
Since it provides three submodels, I answer your question one by one according to my own understanding. But I have no idea about the performance of my model on multi-label cases.

Mix-up (MSD1): You can use this one for multi-label cases. But the performance is hard to say because a mixed-up sample has a new label that looks like a Two-Label classification. That means the model might confuse about whether it is a mixed-up or multi-label sample.

Self-ensemble (MSD2): Of course, you can use it, because the multi-label has no additional limitation on this structure design.

MSD3: It is difficult to apply. This is because a sample distribution for one class is hard to define in a multi-label situation. If you want to apply, you need to figure out how to define one class's sample distribution with model revision.

**Comment by SaraAmd** [comment]
Thank you so much for the response, regarding the mix-up, in the paper it is mentioned that the goal is to have different winning scores and it happens when the labels are mix-up together and multiplying by alpha. Alpha plays an important role for this goal. I think this goal is can also be achieved in multi-label scenario and I thought this component will not have problem being applied on multi-label classification

**Comment by he159ok** [comment]
Hi Sara, 

Sorry for the late reply by not realize the GitHub information.

In my view, the mix-up is hard to explain why it will be effective in the uncertainty estimation of multi-label classification. Concretely, imaging we have a mixed-up label that is [0, 0.4, 0, 0, 0.6], we have no idea whether it is originally a multi-label instance or a mixed-up single-label instance. For implementation, mixed-up can be used to apply to the multi-label case. But for the motivation, it might be strange to me. Maybe a revised mix-up is expected for the multi-label uncertainty estimation.

**Comment by SaraAmd** [comment]
Thank you so much for the explanation

**Comment by he159ok** [comment]
You are welcome.
